version: '3'
services:
  chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    networks:
      - selenium-net

  myapp:
    build: .
    depends_on:
      - chrome
    networks:
      - selenium-net
    volumes:
      - ./data:/app/data  # Map './data' from the host to '/app/data' in the container

networks:
  selenium-net:
    driver: bridge
