version: '3'
services:
  myapp:
    build:
      context: .
    volumes:
      - ./data:/app/data
    depends_on:
      - chrome
    environment:
      - DISPLAY=:99

  chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    shm_size: '2gb'  # Important pour éviter des crashs de Chrome

networks:
  default:
